#' Plot a Summed Probability Distribution (SPD) of Radiocarbon Dates
#'
#' This function plots a summed probability distribution (SPD) for a given radiocarbon date dataset.
#' 
#' @param S A list containing the summed probability distribution, typically generated by the `rowcalsum` function.
#' @param add Logical value indicating whether to add the plot to an existing plot (default is FALSE).
#' @param offset A value to add as an offset to the y-axis (default is 0).
#' @param xlab Label for the x-axis (default 'Automatic' will attempt to label the x-axis given the date range of the SPD).
#' @param ylab Label for the y-axis (default is 'Summed prob.').
#' @param type The type of plot: 'f' for filled polygons, 'l' for lines or 'b' for both.
#' @param col Color for the plot (default is a translucent red).
#' @param lcol Color for lines if type='b' or 'l' (default is to take the value of col).
#' @param lty Line type for the plot (default is 1).
#' @param lwd Line width for the plot (default is 1).
#' @param sm a smoothing parameter; the size of a moving average filter (default is 1). Higher values result in more smoothing.
#' @param ... Additional graphical parameters passed to the `plot` function.
#' 
#' @details
#' This function plots a summed probability distribution for a given radiocarbon date dataset. It can create a new plot or add to an existing plot. The plot type can be either filled polygons or lines.
#' 
#' @examples
#' # Plot a summed probability distribution with filled polygons
#' dates <- data.frame(BP = c(4840, 4885, 4739, 4826, 4610), sd = c(45, 50, 27, 24, 31))
#' spd<-rowcalsum(dates)
#' plot.c14sum(spd)
#'
#' # Plot a summed probability distribution with lines, smoothed and unsmoothed
#' plot.c14sum(spd, type = 'l', col = 1)
#' plot.c14sum(spd, type = 'l', col = 1, lwd = 2, sm=4)
#'
#  @seealso
#' [`rowcalsum`]
#' @export
plot.c14sum<-function(S,add=FALSE,offset=0,xlab='Automatic',ylab='Summed prob.',type='f',col=rgb(0.8,0,0,0.8),lcol=col,lty=1,lwd=1,sm=1,...) {
   if(!(type %in% c('f','l','b'))) stop("'type' must be 'f' for filled polygons, 'l' for lines or 'b' for both")
   # bookend sum with 0s in case the plot is left 'hanging'
   x<-c( S$yrs[1], S$yrs, S$yrs[length(S$yrs)] )
   s<-c( 0, S$sum, 0)
   # replace NAs with 0s to avoid hanging plots
   s[is.na(s)]<-0
   s<-filter(s, rep(1,sm)/sm)
   if (add==FALSE) {
   	plot(x,s,xlab=NA,ylab=ylab,col=NA,...)
   	if(!is.na(xlab)) { if(xlab=='Automatic') { 
       xlab<-'Cal. BC/AD'
       pw<-par('xaxp')
       if(pw[1]>0 & pw[2]>0) xlab<-'Cal. AD'
       if(pw[2]<0) xlab<-'Cal. BC'
  	 }}
  	 title(xlab=xlab)
  	}
   if (type=='f' | type=='b') polygon(c(x[1],x,x[length(x)]),c(offset,s+offset,offset),col=col,border=NA)
   if (type=='l' | type=='b') lines(x,s+offset,col=lcol,lty=lty,lwd=lwd)
}
