#' Plot Bootstrapped Confidence Intervals for a Summed Probability Distribution (SPD)
#'
#' This function plots bootstrapped confidence intervals for a Summed Probability Distribution (SPD).
#'
#' @param SPDb A matrix containing the bootstrapped SPDs (generated by the `SPDboot` function), where each column represents a bootstrap iteration.
#' @param probs A numeric vector specifying the lower and upper percentiles for the confidence intervals (default is c(0.16, 0.84)).
#' @param col Color for the plot (default is a translucent green).
#' @param add Logical value indicating whether to add the plot to an existing plot (default is FALSE).
#' @param fill Logical value indicating whether to fill the area between the confidence intervals (default is TRUE).
#' @param xlab Label for the x-axis (default is 'Automatic').
#' @param ylab Label for the y-axis (default is 'Summed prob.').
#' @param ... Additional graphical parameters passed to the `plot` function.
#'
#' @details
#' This function plots bootstrapped confidence intervals for a given SPD. It calculates the specified percentiles for the bootstrapped SPDs and plots the upper and lower bounds as lines. If `fill` is TRUE, it fills the area between the confidence intervals with the specified color.
#'
#' The function can create a new plot or add to an existing plot, with customizable x-axis and y-axis labels, plot colors, and other graphical parameters.
#'
#' @examples
#' # Plot bootstrapped confidence intervals for a SPD
#' dates <- data.frame(BP = c(4840, 4885, 4739, 4840, 4885, 4239, 4840, 4845, 4739, 4826, 4610), sd = c(45, 50,60,30, 27, 30, 33, 45, 23, 24, 31))
#' S<-rowcalsum(dates)
#' Sboot<-SPDboot(S)
#' plot(Sboot, col = "#8888FF20")
#' lines(median(Sboot), col="#5050FF")δ
#'
#  @seealso
#' [`SPDboot`] ['median.SPDboot']
#' @export
plot.SPDb <- function(SPDb, probs = c(0.16, 0.84), col = rgb(0.1, 0.7, 0.1, 0.8), add = FALSE, fill = TRUE, xlab = 'Automatic', ylab = 'Summed prob.', ...) {
  sy <- summary(SPDb, probs = probs)
  x <- as.numeric(rownames(SPDb))
  U <- sy[, 2]
  L <- sy[, 1]
  if (add == FALSE) {
    plot(x, U, xlab = NA, ylab = ylab, col = NA, ...)
    if (!is.na(xlab)) {
      if (xlab == 'Automatic') {
        xlab <- 'Cal. BC/AD'
        pw <- par('xaxp')
        if (pw[1] > 0 & pw[2] > 0) xlab <- 'Cal. AD'
        if (pw[2] < 0) xlab <- 'Cal. BC'
      }
    }
    title(xlab = xlab)
  }
  lines(x, U, lwd = 1, col = col)
  lines(x, L, lwd = 1, col = col)
  if (fill == TRUE) polygon(c(x, rev(x)), c(U, rev(L)), col = col, border = NA)
}
